### ISSUE TITLE
T0 ARMOR+ BONUSES

### ISSUE THREAD

**Issue by warius1983** [datchannin/Brothers-WoW#42]
![](https://i.imgur.com/IrQdYR2.png)

![](https://media.discordapp.net/attachments/720587456545685525/772848235105878026/unknown.png)

**Comment by warius1983** [comment]
Ok let's start Bonus Sets:

WARRIOR
body:
Helm:
Shoulder:
Set Bonus:

PALADIN
body:
Helm:
Shoulder:
Set Bonus:

HUNTER
body:
Helm:
Shoulder:
Set Bonus:

DRUID
body:
Helm:
Shoulder:
Set Bonus:

ROGUE
body:
Helm:
Shoulder:
Set Bonus:

MAGE
body:
Helm:
Shoulder:
Set Bonus:

PRIEST
body:
Helm:
Shoulder:
Set Bonus:

WARLOCK
body:
Helm:
Shoulder:
Set Bonus:

**Comment by datchannin** [comment]
I've added shoulders bonus - only passive increase some character stats.
Body + Helmet give bonuses for some perks.
Set - also bonus for perks.

I've added some ranged defense for characters, because some of them does not have this parameters, so them can be killed from 1-2 arrows in the first turn.

Warrior - OK

Paladin - OK (aura are setup for all characters without paladin. Paladin only can activate/deactivate effect, I can not change radius, paladin checker is after radius checker used)

Hunter - OK

Druid - OK

Rogue - OK (Usually does not level ranged defense, so it can be useful. But may be change initiative perk to give +10 fatigue instead of endurance +10 ranged defense).

Mage - OK (shoulders ranged defense can be changed to hitpoints+fatigue, like from Warlock)

Priest - OK (shoulders ranged defense can be changed to hitpoints+fatigue, like from Warlock, as you said priest endgame heal is powerful enough, so I did not add more base power. shoulders I want use for stats bonus, not for perk updates. May be update this set bonus to + base heal power?)

Warlock - OK (characters may be updated in next version, but sets should be used for this mod version)

Armor Value:
Druid uses leather armor, the same as rogue. So may be it will be better to use values from rogue armor set.

**Comment by warius1983** [comment]
Armor Value:
Druid uses leather armor, the same as rogue. So may be it will be better to use values from rogue armor set.
OK

Hunter shoulders: 10% pet life?

For the rest It may go like this at the moment i don't have particular issues only the druid was sounding a little strange

**Comment by datchannin** [comment]
All sets and items bonuses were implemented, can be tested now.
This is current variant.
![image](https://user-images.githubusercontent.com/39913306/98159617-f4ea2480-1eed-11eb-8ada-1cda120eb4a8.png)

**Comment by warius1983** [comment]
Ok i will see if there will be any bugs if detectable

**Comment by datchannin** [comment]
T0 armor and bonuses were implemented from version 0.90.
Done and close.
